version: '3.8'

services:
  backend:
    image: polwro-backend:latest
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./data:/data # Udostępnij katalog danych dla backendu
    environment:
      - DATABASE_URL=sqlite:///data/mydatabase.db # Zdefiniuj URL bazy danych
    command: sh -c "npm install && npm start" # Uruchom backend

  frontend:
    image: polwro-frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001 # Adres API backendu
      - CHOKIDAR_USEPOLLING=true # Dla systemów Windows
      #- NODE_OPTIONS=--openssl-legacy-provider
    command: sh -c "npm start" # Uruchom frontend

volumes:
  data: # Zdefiniuj wolumen dla danych