version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py

  frontend:
 #   image: greedy-polwro-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    environment:
      - CHOKIDAR_USEPOLLING=true  # Dodatkowe ustawienie dla systemów Windows
      - NODE_OPTIONS=--openssl-legacy-provider