version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
